name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  larastan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Rodar Larastan
        run: composer analyse

      - name: Executar verificação de estilo (linter)
        run: composer lint